### ISSUE TITLE
Packaging for Fedora

### ISSUE THREAD

**Issue by hakavlad** [facebookincubator/oomd#90]
Fedora Rawhide is ready to oomd packaging. Cgroup2 is used by default and swapaccount is enabled by default.

**Comment by filbranden** [comment]
RPMs for the just released oomd v0.2.0 are available on this COPR repository:
https://copr.fedorainfracloud.org/coprs/filbranden/oomd/

Feel free to use them and please report back on how they work for you!

I'm also going to propose them for inclusion on Fedora.

Cheers,
Filipe

**Comment by filbranden** [comment]
Proposed for inclusion on Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1750983

**Comment by hakavlad** [comment]
Please add this here https://github.com/facebookincubator/oomd#building-and-installing

**Comment by filbranden** [comment]
Will do. Preparing a PR for that right now.

**Comment by danobi** [comment]
> They kill all the session instead of one process.

Yeah this is most unfortunate. There's been some discussion on the fedora mailing lists about getting gnome to start applications [in their own user slices][https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/MML5MAKBFNEXBT67TCOVUWGFNOUDYUUP/]. This would be more in line with how we handle things in the data center. Each cgroup should be a logical block of the system. It's kind of clowny to put all user applications in the same cgroup.

> They uses 7% CPU on my VM.

This has been fixed in upstream linux. It used to be an O(N) operation to read memory.stat in a cgroup (N is the number cgroups alive and non-reclaimed yet). Now it will be O(1).

> I turned off the swap and started opening browser tabs, and in the end the system freezed.

oomd needs swap. If configured correctly (see point 1), oomd will prevent swap thrashing. In theory that makes swap only useful and not bad.

**Comment by danobi** [comment]
> I would like you to honestly document the disadvantages of using oomd on the desktop somewhere.

I noticed you have a short state-of-the-world in your nohang repo. I would take a patch for a wiki page in this repo for a description if you're interested.

**Comment by hakavlad** [comment]
>if you're interested

yes, please (but I do not quite understand what you mean)

**Comment by filbranden** [comment]
Just wanted to leave a note here that `oomd-0.2.0-4` is available on Fedora Rawhide already. (So you don't even need the COPR repository there.)

I opened tickets to push it to Fedora 31 and 30 as well (since they seem to have most of the pre-requisites available), so it may end up being included by default there.

I'll be releasing new versions of oomd to Fedora as they become available, so feel free to push fixes, new features and docs upstream and they'll eventually get into the Fedora package.

I believe this issue can be closed now, since I'd say inclusion in Fedora has been completed.

Regarding the fixes on documentation and including a state-of-the-world, perhaps this should be done on a separate issue? But feel free to keep having the discussion on this one (either keeping it closed or reopened) if you feel like this is still the place for it.

Cheers!
Filipe
